# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demoes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Swiftent', '~> 0.0.13'
pod 'UMeng', '~> 2.2.1'
pod 'RongCloudIM', '~> 2.8.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'Alamofire', '3.5.1'


end
